advt_norm: false
algo: ppo
all_train: false
batch_size: 0
curiosity: false
curiosity_ratio: 0.5
data_norm: false
device: cpu
episode_length: 500
ext_ratio: 0.5
game_name: olympics-running
load_episode: 300
load_model: false
load_run: 1
log: true
map: 1
max_episodes: 1500
max_length: 500
num_rollouts: 22
popart: false
render: false
reward_norm: false
save_interval: 10
seed: 1
shuffle_map: false
task_num: 11
use_astar: false
use_cnn: false
use_onehot: false
