advt_norm: true
algo: ppo
curiosity: true
curiosity_ratio: 0.9
data_norm: true
device: cpu
episode_length: 500
ext_ratio: 0.1
game_name: olympics-running
load_episode: 300
load_model: false
load_run: 1
log: true
map: 1
max_episodes: 1500
num_rollouts: 36
render: false
reward_norm: true
save_interval: 1
seed: 1
shuffle_map: true
